* :doc:`/customers/profile_details/loyalty/introduction`
* :doc:`/customers/profile_details/loyalty/loyalty`
* :doc:`/customers/profile_details/loyalty/profitability`
* :doc:`/customers/profile_details/loyalty/transactions`
* :doc:`/customers/profile_details/loyalty/transfer`
* :doc:`/customers/profile_details/loyalty/available_rewards`
* :doc:`/customers/profile_details/loyalty/redeemed_rewards`



